-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0
NDefines.NDiplomacy.LONG_REIGN_YEARS_START = 100
NDefines.NDiplomacy.RETIRE_TO_MONASTERY_INTERACTION_PIETY = 100000
NDefines.NDiplomacy.RETIRE_TO_MONASTERY_INTERACTION_ENABLED = 0	
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_PIETY = 10000
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_PRESTIGE = 0
NDefines.NCharacter.WRONG_GOV_FORM_TAX_MOD = 0
NDefines.NCharacter.WRONG_GOV_FORM_LEVY_MOD = 0
NDefines.NCharacter.PORTRAIT_MID_AGE_THRESHOLD = 240				
NDefines.NCharacter.PORTRAIT_OLD_AGE_THRESHOLD = 1600
NDefines.NCharacter.AGE_OLD = 1000								
NDefines.NCharacter.AGE_VERY_OLD = 2000
NDefines.NCharacter.NOT_SPOUSE_FERTILITY_MULT = 0.25
NDefines.NCharacter.MALE_ATTRACTION_CUTOFF = 1000					
NDefines.NCharacter.FEMALE_ATTRACTION_CUTOFF = 1000	
NDefines.NCharacter.MAX_CROWN_LAW_CHANGES = 1
NDefines.NMilitary.MERCENARY_MAINTENANCE_FACTOR = 100
NDefines.NMilitary.MERCENARY_VASSAL_MAINTENANCE_FACTOR = 0.5		
NDefines.NMilitary.MERCENARY_HIRE_COST_FACTOR = 1.0
NDefines.NMilitary.HOLY_ORDER_HIRE_COST_FACTOR = 1.0
NDefines.NMilitary.MAX_LEADERSHIP_TRAITS = 10
NDefines.NAI.BASE_AI_ARMY_SIZE = 100