-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.DEMESNE_BASE_MAX_SIZE = 2.0
NDefines.NDiplomacy.LONG_REIGN_YEARS_START = 50
NDefines.NDiplomacy.MAX_LONG_REIGN_BONUS = 20
NDefines.NDiplomacy.RETIRE_TO_MONASTERY_INTERACTION_PIETY = 100000
NDefines.NDiplomacy.RETIRE_TO_MONASTERY_INTERACTION_ENABLED = 0	
NDefines.NCharacter.WRONG_GOV_FORM_TAX_MOD = 0
NDefines.NCharacter.WRONG_GOV_FORM_LEVY_MOD = 0
NDefines.NCharacter.PORTRAIT_MID_AGE_THRESHOLD = 30					
NDefines.NCharacter.PORTRAIT_OLD_AGE_THRESHOLD = 9000
NDefines.NCharacter.AGE_OLD = 2000								
NDefines.NCharacter.AGE_VERY_OLD = 3000
NDefines.NCharacter.NOT_SPOUSE_FERTILITY_MULT = 0.25
NDefines.NCharacter.MALE_ATTRACTION_CUTOFF = 3000					
NDefines.NCharacter.FEMALE_ATTRACTION_CUTOFF = 3000	
NDefines.NCharacter.MAX_CROWN_LAW_CHANGES = 10
NDefines.NMilitary.MAX_LEADERSHIP_TRAITS = 5
NDefines.NGraphics.NUMBER_OF_PROPERTIES = 19
NDefines.NAI.BASE_AI_ARMY_SIZE = 10000
NDefines.NAI.AI_ASSAULT_RATIO = 2
NDefines.NMilitary.MERCENARY_MAINTENANCE_FACTOR = 100
NDefines.NMilitary.MERCENARY_VASSAL_MAINTENANCE_FACTOR = 0.5		
NDefines.NMilitary.MERCENARY_HIRE_COST_FACTOR = 1.0
NDefines.NMilitary.HOLY_ORDER_HIRE_COST_FACTOR = 1.0
NDefines.NMilitary.SPECIAL_TROOPS_GRAPHICAL_FACTOR = 500
NDefines.NMilitary.HOLDING_LEVY_SIZE_OWNER_MARTIAL_BASE = 0.800
NDefines.NMilitary.HOLDING_LEVY_SIZE_OWNER_MARTIAL_MULT = 0.02
NDefines.NMilitary.COMMAND_MODIFIER_MARTIAL_MULTIPLIER = 0.02
NDefines.NMilitary.RETINUE_FROM_REALMSIZE = 0.5
NDefines.NTechnology.DONT_EXECUTE_TECH_BEFORE = 1506
NDefines.NTechnology.IDEAL_YEAR_LEVEL_0 = 1506
NDefines.NTechnology.IDEAL_YEAR_LEVEL_8 = 1800
NDefines.NRulerDesigner.MAX_AGE = 900

